config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  devise_for :users,
  controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

    resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end
  
  resources :card, only: [:index, :new, :show, :delete] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:index,:show,:new, :edit]

  resources :mypage, only: [:index] do
    get "profile"
  end
  resources :logout, only: [:index]

  resources :sell, only: [:index,:new, :create, :destroy]
  resources :items, only: [:index,:new,:show,:edit,:update,:destroy] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
      get "before_edit"
    end
  end
  resources :profile, only: [:index]
  resources :card, only: [:index] do
    collection do
      get 'mypage_card_input'
    end
  end
  resources :pribate, only: [:index]
  resources :confomation, only: [:index]
  resources :buy, only: [:index] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
    end
  end

  
  get "/mypage/exhibiting", to: "mypage#exhibiting"
  get '/mypage/notification', to: 'mypage#notification'
  get '/mypage/todo', to: 'mypage#todo'
  get '/mypage/card', to: 'mypage#card'
  get '/mypage/deliver_address', to: 'mypage#deliver_address'
  delete '/card/delete', to: 'card#delete'



end

app/views/index/_bread-crumbs.html.haml
.bread-crumbs
  = breadcrumbs pretext: '', separator: ' &rsaquo; ', class: 'breadcrumbs-list'

app/views/index/_download.html.haml
.download
  .download__text
    .download__text__upper
      スマホで簡単フリマアプリ
    .download__text__bottom
      今すぐ無料ダウンロード！
  .download__image
    .download__image__logo
      = image_tag "logo_red.svg"
    .download__image__apple
      = link_to  "https://www.apple.com/jp/ios/app-store/" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg'
    .download__image__google
      = link_to  "https://play.google.com/store?utm_source=apac_med&utm_medium=hasem&utm_content=Dec0419&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-jp-1003227-med-hasem-py-Evergreen-Dec0419-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012434507671_creativeid_114860667305_device_c_kwd_kwd-33891114176_geoid_1009308_network_g&gclid=Cj0KCQiAz53vBRCpARIsAPPsz8UTsjCRfkQGH6uZuYax5jBYw-4GKUg1D6SwDcYv3I-ZNXPmNiYO58gaAp6-EALw_wcB&gclsrc=aw.ds" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg' 

app/views/index/_during_trade.html.haml
.exhibing-all
  .exhibing-all__title
    購入した商品
  %ul.list-tabs
    %li.during_trade-tab
      = link_to "#",class: "during_trade-list" do
        取引中
    %li.during_trade-tab
      = link_to "#",class: "during_trade-list" do
        過去の取引
  .like_list
    %ul.mypage-item-list
      %li#mypage-item-none 
        取引中の商品がありません

app/views/index/_exhibit.html.haml
- if user_signed_in?
  = link_to new_sell_path, class: "footer-exhibit" do
    %div#exhibit-text
      出品
    %i.fa.fa-camera
- else
  = link_to signup_index_path, class: "footer-exhibit" do
    %div#exhibit-text
      出品
    %i.fa.fa-camera

app/views/index/_footer.html.haml
.mainfooter
  .mainfooter__contents
    .mainfooter__contents__first
      %h4.mainfooter__contents__title フリマについて
      %ul.mainfooter__contents__list
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            会社概要（運営会社）
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            採用情報
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            プレスリリース
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            公式ブログ
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            フリマ利用ガイドライン
        .mainfooter__contents__icon
          = link_to '#', class: "link-icon" do
            = fa_icon 'twitter', class: 'footer-icon'
          = link_to '#', class: "link-icon" do
            = fa_icon 'facebook-square', class: 'footer-icon'
        
    
    .mainfooter__contents__second
      .mainfooter__contents__title 
        ヘルプ&ガイド
      %ul.mainfooter__contents__list
        %li.mainfooter__contents__link__link
          = link_to '#', class: "link-link" do
            フリマガイド
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            らくらくフリマ便
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            ゆうゆうフリマ便
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            大型フリマ便
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            車体取引ガイド
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            フリマあんしん・あんぜん宣言！
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            偽ブランド品撲滅への取り組み
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            フリマボックス

    .mainfooter__contents__third
      %h4.mainfooter__contents__title プライバシーと利用規約
      .mainfooter__contents__top
        .mainfooter__contents__left
          %ul.mainfooter__contents__list
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                プライバシーポリシー
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                フリマ利用規約
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                安心スマホサポート制度に関する利用特約
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                コンプライアンスポリシー
              
        
        .mainfooter__contents__right
          %ul.mainfooter__contents__list
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                個人データの安全に管理に係る基本方針
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                特定商取引に関する表記
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                資産決済方に基づく表示
            %li.mainfooter__contents__link
              = link_to '#', class: "link-link" do
                法令順守と犯罪抑止のために
    
    .mainfooter__contents__last
      %h4.mainfooter__contents__title 国
      %ul.mainfooter__contents__ul
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            日本
        %li.mainfooter__contents__link
          = link_to '#', class: "link-link" do
            United States

  .footer-log
    =link_to "", class: "footer-log__first" do
      = image_tag "fmarket_logo_white.svg", class: "footer-logo__img"
    .footer-log__copy
      %small © Furima, Inc.

app/views/index/_header.html.haml
.header
  .main-header
    .main-header-top
      .main-header-logo
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg"
      .mainheader-logo-search
        %input.mainheader-logo-search-box{placeholder: "何かお探しですか？", type: "text", value: ""}
        %button.mainheader-logo-search-button
          %i.fa.fa-search

    .main-header-bottom
      .main-header-bottom__left 
        .main-header-bottom-leftbox
          .a-category
            %i.fa.fa-bars.headericon
            = link_to "/",class:"a-category" do
              カテゴリーから探す
          .a-brand
            %i.fa.fa-tags.headericon
            = link_to "/",class:"a-brand" do
              ブランドから探す
      .main-header-bottom__right1
      - if user_signed_in?
        %ul.main-header-bottom__right2
          = link_to "/",class: "headerlike" do
            %i.fa.fa-heart-o
            %span.header-bottom-icon いいね一覧
          = link_to mypage_notification_path,class: "headerlike" do
            %i.fa.fa-bell-o
            %span.header-bottom-icon お知らせ
          = link_to mypage_todo_path,class: "headerlike" do
            %i.fa.fa-check
            %span.header-bottom-icon やることリスト
          = link_to mypage_index_path , class: "header-bottom-icon" do
            = image_tag "member.png", class: "header-mypageicon"
            マイページ
      - else

        .main-header-bottom__right1
          .main-header-bottom__right1-signup
            = link_to '新規会員登録', signup_index_path, class: "a-signup"
          .main-header-bottom__right1-login
            = link_to 'ログイン', new_user_session_path,method: :get, class: "a-login"

app/views/index/_header_image.html.haml
.headerimage
  .headerimage__text
    .headerimage__text__upper
      スマホでかんたん
      %br/
      フリマアプリ
    .headerimage__text__bottom
      フリマはスマホカメラからすぐに出品できる
      %br/
      購入時も安心な独自システムのアプリです
  .headerimage__image
    .headerimage__image__apple
      = link_to  "https://www.apple.com/jp/ios/app-store/" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg', height: "50", width: "170"
    .headerimage__image__google
      = link_to  "https://play.google.com/store?utm_source=apac_med&utm_medium=hasem&utm_content=Dec0419&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-jp-1003227-med-hasem-py-Evergreen-Dec0419-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012434507671_creativeid_114860667305_device_c_kwd_kwd-33891114176_geoid_1009308_network_g&gclid=Cj0KCQiAz53vBRCpARIsAPPsz8UTsjCRfkQGH6uZuYax5jBYw-4GKUg1D6SwDcYv3I-ZNXPmNiYO58gaAp6-EALw_wcB&gclsrc=aw.ds" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg', height: "50", width: "170"

app/views/index/_header_image2.html.haml
.headerimage2

app/views/index/_mypage_sidebar.html.haml
.mypage_side
  %ul#mypage_side__list
    %li
      = link_to "#",class: "mypage_side__list__item" do
        マイページ
    %li
      = link_to "#",class: "mypage_side__list__item" do
        お知らせ
    %li
      = link_to "#",class: "mypage_side__list__item" do
        やることリスト
    %li
      = link_to "#",class: "mypage_side__list__item" do
        いいね！一覧
    %li
      = link_to "#",class: "mypage_side__list__item" do
        出品する
    %li
      = link_to "#",class: "mypage_side__list__item" do
        出品出品した商品 - 出品中
    %li
      = link_to "#",class: "mypage_side__list__item" do
        出品出品した商品 - 取引中
    %li
      = link_to "#",class: "mypage_side__list__item" do
        出品出品した商品 - 売却中
    %li
      = link_to "#",class: "mypage_side__list__item" do
        購入した商品 - 取引中
    %li
      = link_to "#",class: "mypage_side__list__item" do
        購入した商品 - 過去の過去の取引
    %li
      = link_to "#",class: "mypage_side__list__item" do
        ニュース一覧
    %li
      = link_to "#",class: "mypage_side__list__item" do
        評価一覧
    %li
      = link_to "#",class: "mypage_side__list__item" do
        ガイド
    %li
      = link_to "#",class: "mypage_side__list__item" do
        お問い合わせ
  .mypage_side__title
    フリペイ
  %ul#mypage_side__list
    %li
      = link_to "#",class: "mypage_side__list__item" do
        売上・振込申請
    %li
      = link_to "#",class: "mypage_side__list__item" do
        ポイント
  .mypage_side__title
    設定
  %ul#mypage_side__list
    %li
      = link_to "#",class: "mypage_side__list__item" do
        プロフィール
    %li
      = link_to "#",class: "mypage_side__list__item" do
        発送元・お届け先住所変更
    %li
      = link_to "#",class: "mypage_side__list__item" do
        支払い方法
    %li
      = link_to "#",class: "mypage_side__list__item" do
        メール/パスワード
    %li
      = link_to "#",class: "mypage_side__list__item" do
        本人情報
    %li
      = link_to "#",class: "mypage_side__list__item" do
        電話番号の確認
    %li
      = link_to "#",class: "mypage_side__list__item" do
        ログアウト

app/views/index/_payment.html.haml
.payment
  .payment__content
    .payment__content--container
      %h2.payment__content--head
        支払い方法
      .payment__content

app/views/index/_registration_header.html.haml
.registration
  .registration-header
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "logo"
  %nav.progress
    %ul.progress-bar
      %li.through#through
        会員情報
        .progress-status
        .progress-status_bar
      %li.active#active
        電話番号認証
        .progress-status
        .progress-status_bar
      %li.address#address
        お届け先住所入力
        .progress-status
        .progress-status_bar
      %li.payment#payment
        支払い方法
        .progress-status
        .progress-status_bar
      %li.end#end
        完了
        .progress-status
        .progress-status_bar

app/views/index/_slick.html.haml
%div.slick
  %div
    = render "header_image"
  %div
    = render "header_image2"

app/views/index/index.html.haml
.wrapper
  = render "header"
  = render "exhibit"
  = render "slick"
  = render "items/mainindex"
  = render "download"
  = render "footer"
  

app/views/index/login_forget.html.haml
= render 'shared/user_header'
.login_forget
 .login_forget__container
  .login_forget__container__title
   パスワードをお忘れの方
  .login_forget__container__mail_address
   メールアドレス
   = form_with(model:@adress) do |f|
    .login_forget__container__mail_address_form
    = f.email_field :email, placeholder: "ご登録されたメールアドレス", class: "mail_address"
    .login_forget__container__mail_address_text
     ご登録されたメールアドレスにパスワード再設定のご案内が送信されます。
    .login_forget__container__robot
    %script{async: "#", defer: "", :src => "https://www.google.com/recaptcha/api.js"}
    %form{action:  "./verify.php", method: "POST"}
    .g-recaptcha{"data-sitekey": "サイトキー"}
    .login_forget__container__send_btn
    = f.submit :送信する, class: "send-btn"
= render 'shared/user_footer'