config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  devise_for :users,
  controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

    resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end
  
  resources :card, only: [:index, :new, :show, :delete] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:index,:show,:new, :edit]

  resources :mypage, only: [:index] do
    get "profile"
  end
  resources :logout, only: [:index]

  resources :sell, only: [:index,:new, :create, :destroy]
  resources :items, only: [:index,:new,:show,:edit,:update,:destroy] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
      get "before_edit"
    end
  end
  resources :profile, only: [:index]
  resources :card, only: [:index] do
    collection do
      get 'mypage_card_input'
    end
  end
  resources :pribate, only: [:index]
  resources :confomation, only: [:index]
  resources :buy, only: [:index] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
    end
  end

  
  get "/mypage/exhibiting", to: "mypage#exhibiting"
  get '/mypage/notification', to: 'mypage#notification'
  get '/mypage/todo', to: 'mypage#todo'
  get '/mypage/card', to: 'mypage#card'
  get '/mypage/deliver_address', to: 'mypage#deliver_address'
  delete '/card/delete', to: 'card#delete'



end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :seler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  has_many :images, dependent: :destroy
  has_many :brands, dependent: :destroy
  has_many :category,through: :item_categories
  has_many :item_categories, dependent: :destroy
  accepts_nested_attributes_for :images,allow_destroy: true
  accepts_nested_attributes_for :brands,allow_destroy: true
  accepts_nested_attributes_for :item_categories,allow_destroy: true

  has_many :categories, through: :items_categories
  has_one :brand
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, inclusion: 300..9999999
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:index, :show, :edit, :destroy, :buyscreen, :buyscreenitem]
  def index
    @items = Item.find(set_item[:id]).limit(10).order('created_at DESC')
    @images = Image.find(set_item[:id])
    @image = Image.find(item_id: image_params)
    @item = Item.find(set_item[:id])
    @item.update( buyer_id: current_user.id)
  end

  def new
    @item = Item.new
    @item.images.build
    @item.item_categories.build
    @item.brands.build
  end

  def show
    @category = Category.find(params[:id])
    @images = Image.where(item_id:@item.id)
    @image = @images
    @brand = Brand.find_by(item_id:@item.id)
    @user = User.find(@item.seler_id)
  end

  def buyscreen
    @images = Image.where(item_id:@item.id)
    @image = @images[0]
    @addresses = Address.where(user_id: current_user.id)
    @address = @addresses[0]
    if @item.seler_id == current_user.id
      redirect_to before_edit_item_path
    else
      @item.buyer_id = current_user.id
    end
    @item.save
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:"pay.jp"][:"PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  def buyscreenitem

  end

  def update
    @item = Item.find(params[:id])
    @images = @item.images
    if @item.update!(update_item_params)
      # params[:images][:image].each do |image|
      #   @item.images.create!(image: image, item_id: @item.id)
      # end
      redirect_to before_edit_item_path(params[:id]), notice: "編集しました"
      else
    end

  end
  def edit
    @item = Item.find(params[:id])
  end

  def before_edit
    @item = Item.find(params[:id])
    @images = Image.where(item_id:@item.id)
    @image = @images
    @brand = Brand.find_by(item_id:@item.id)
    @user = User.find(@item.seler_id)
    @category = Category.find(params[:id])
  end

  def destroy
    if @item.seler_id == current_user.id &&@item.destroy
      redirect_to root_path
    else
    end
  end


  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(
      :name,
      :price,
      :description,
      :date,
      :status,
      :burden,
      :send_method,
      :region,
      item_categories_attributes: [:category_id],
      brands_attributes: [:name]).merge(seler_id: current_user.id)
  end

  def update_item_params
    params.require(:item).permit(
      :name,
      :price,
      :description,
      :date,
      :status,
      :burden,
      :send_method,
      :region,
      item_categories_attributes: [:category_id, :_destroy],
      brands_attributes: [:name, :_destroy],
      images_attributes: [:image, :_destroy]).merge(seler_id: current_user.id)
  end



  def image_params
    @image = Image.find(params[:id])
  end
end
  

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_buyindex.html.haml
.buy-item-wrapper
  .buy-item-header
    = link_to root_path do
      .buyitem-header__logo
        = image_tag "fmarket_logo_white.svg"
  .buy-item-contents
    .buy-detail 
      %h1.buy-detail-data 購入内容の確認
    .buy-item
      .buy-item-contents
        .buy-item-contents__content
          .buy-item-contents__content__image
            = image_tag @image.image.url
          .buy-item-contents__content__main
            .buy-item-contents__content__main__name
              = @item.name  
            .buy-item-contents__content__main__price
              = "¥#{@item.price}"
              %span.buy-item-burden
                = @item.burden
      .buy-item-bottom
        .buy-item-bottom__price
          .buy-item-bottom__price__top
            .buy-item-bottom__price__top__name
              支払い金額
            .buy-item-bottom__price__top__price
              = "¥#{@item.price}"
          .buy-item-bottom__price__bottom
        .buy-item-bottom__pay
          %h2.buy-item-pay 支払い方法
          - if @default_card_information != nil
            = image_tag "visa.svg", class: "card-logo-svg"
            .card__nam
              = "**** **** **** " + @default_card_information.last4
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            .item-bottom__pay__month
              = exp_month + " / " + exp_year
          - else
        .buy-item-bottom__purchase
          .buy-item-bottom__purchase__title
            .buy-item-bottom__purchase__title__delivery
              %h3.buy-delivery 配送先
            .buy-item-bottom__purchase__title__change
              %span 変更する
          .buy-item-bottom__purchase__main  
            .buy-item-bottom__purchase__main__post
              = "〒#{@address.postal_code}"
            .buy-item-bottom__purchase__main__address
              = "#{@address.prefecture_id} #{@address.city} #{@address.address}"
            .buy-item-bottom__purchase__main__name 
              = current_user.nickname
        .item-bottom__buy-btn
          = form_with url: buyscreenitem_item_path(@item) , method: :post,local:true do |f|
            = f.hidden_field :user_id,value:current_user.id
            = f.hidden_field :item_id,value:@item.id
            - if @default_card_information != nil
              = f.submit value:"購入する", class: "buy-btn"
            - else  
              .not 購入できません
  .buy-item-footer
    %ul.buy-item-footer__ul
      %li.buy-item-footer__ul__li
        = link_to "プライバシーポリシー", root_path
      %li.buy-item-footer__ul__li
        = link_to "メルカリ利用規約", root_path
      %li.buy-item-footer__ul__li
        = link_to "特定商取引に関する表記", root_path
    = image_tag "logo_gray.svg"

app/views/items/_delete_item.html.haml
%section.itembuy-content
  %h1.itembuy-content__name
    = @item.name
  .itembuy-content__clearfix
    .itembuy-content__photo
      = render "item_carusel"
    %table.itembuy-content__table
      %tbody
        %tr
          %th.thcategory 出品者
          %td.tdcategory
            = link_to '/' , class:'tdcategory-name' do
              = @user.nickname
            %div
              .itembuy-user-evaluation-smile
                %i.fa.fa-smile-o
                %span.evaluation-icon 999
              .itembuy-user-evaluation
                %i.fa.fa-meh-o
                %span.evaluation-icon 999
              .itembuy-user-evaluation
                %i.fa.fa-frown-o
                %span.evaluation-icon 999
        %tr
          %th.thcategory カテゴリー
          %td.tdcategory
            = link_to  '/' do
              カテゴリ
              .itembuy-table-sub
                %i.fa.fa-chevron-right
                テスト
            = link_to '/' do
              .itembuy-table-sub
                %i.fa.fa-chevron-right
                テスト
        %tr
          %th.thcategory  ブランド
          %td.tdcategory
            = link_to '/' do
              ブランド
        %tr
          %th.thcategory 商品の状態
          %td.tdcategory
            = @item.status
        %tr
          %th.thcategory 配送料の負担
          %td.tdcategory
            = @item.burden
        %tr
          %th.thcategory 配送の方法
          %td.tdcategory
            = @item.send_method
        %tr
          %th.thcategory 配送元地域
          %td.tdcategory
            = link_to '/' do
              = @item.region
        %tr
          %th.thcategory 発送日の目安
          %td.tdcategory
            = @item.date
  .itembuy-content__price
    %span.itembuy-content__bold
      = @item.price
    %span.itembuy-content__tax (税込)
    %span.itembuy-content__taxfee
      送料込み

  .itembuy-detail
    %p.itembuy-detail__coments
      
  .itembuy-content__button
    .itembuy-content__push
      = link_to edit_item_path, class:"item-edit" do
        商品の編集
      %p.itembuy-content__Separator
        or
      = link_to '/', class:"item-resume" do
        出品を再開する
      %p.item-btn
        = link_to item_path, method: :delete, class:"item-delete" do
          この商品を削除する

  .itembuy-content-box
    .itembuy-detail-message
      .itembuy-content__comment
        %form.itembuy-message__form
          %p.form-messeage-coments 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea.form-messeage-textarea
          %button.form-messeage-button
            %span コメントする

app/views/items/_item_carusel.html.haml
%div.thumb-item
  - @images.each do |image|
    %div
      = image_tag image.image.url, class: 'owl-stage-outer', size: '300x300'
%div.thumb-item-nav
  - @images.each do |image|
    %div.item_carusel
      = image_tag image.image.url, class: 'owl-stage-outer-sub', size: '60x60'

app/views/items/_mainindex.html.haml
.main-category
  %h2.main-category-top 人気のカテゴリー
  .main-category-bottom
    %ul.category-items
      %li.category-item-btn
        %a.category-item-name レディース
      %li.category-item-btn
        %a.category-item-name メンズ
      %li.category-item-btn
        %a.category-item-name 家電・スマホ・カメラ
      %li.category-item-btn
        %a.category-item-name おもちゃ・ホビー・グッズ
.main-items
  .main-items-show
    .main-items-show-header
      %h3.main-items-show-header-left 新着アイテム
      = link_to 'もっと見る >', '#', class: 'main-items-show-header-right'
    .main-items-show-bottom
      .main-items-bottom-list
        %ul.list-items
          - @items.each do |item|
            %li.list-item
              .list-item-all
                = link_to item_path(item.id), class:"main-items-all", method: :get do
                  %figure.main-items-all-figure
                    .img-main-item1
                      = image_tag item.images[0].image.url ,class: "img-main-item",size:"188x188"
                      -if item.buyer_id.present?
                        .items-box_photo__all
                          .items-box_photo__sold
                            .items-box_photo__sold__inner
                              SOLD
                      - else
                      %span.aria-label
                        = "¥#{item.price}"
                    %figcaption.main-items-all-figure-i
                      %span.main-items-all-span
                        = item.name

app/views/items/_product_show.html.haml
%section.itembuy-content
  %h1.itembuy-content__name
    = @item.name
  .itembuy-content__clearfix
    .itembuy-content__photo
      = render "item_carusel"
    %table.itembuy-content__table
      %tbody
        %tr
          %th.thcategory 出品者
          %td.tdcategory
            = link_to root_path , class:'tdcategory-name' do
              = @user.nickname
            %div
              .itembuy-user-evaluation-smile
                %i.fa.fa-smile-o
                %span.evaluation-icon 999
              .itembuy-user-evaluation
                %i.fa.fa-meh-o
                %span.evaluation-icon 999
              .itembuy-user-evaluation
                %i.fa.fa-frown-o
                %span.evaluation-icon 999
        %tr
          %th.thcategory カテゴリー
          %td.tdcategory
            = link_to  root_path ,class: "link_color"do
              = @category.name
        %tr
          %th.thcategory  ブランド
          %td.tdcategory
            = link_to root_path,class: "link_color" do
              = @brand.name
        %tr
          %th.thcategory 商品の状態
          %td.tdcategory
            = @item.status
        %tr
          %th.thcategory 配送料の負担
          %td.tdcategory
            =@item.burden
        %tr
          %th.thcategory 配送の方法
          %td.tdcategory
            = @item.send_method
        %tr
          %th.thcategory 配送元地域
          %td.tdcategory
            = link_to root_path ,class: "link_color"do
              = @item.region
        %tr
          %th.thcategory 発送日の目安
          %td.tdcategory
            = @item.date
  .itembuy-content__price
    %span.itembuy-content__bold
      ¥
      = @item.price
      
    %span.itembuy-content__tax (税込)
    %span.itembuy-content__taxfee
      送料込み
    - if @item.buyer_id.present? 
      .itembuy-price-box-sold
        売り切れました
    - else
      .itembuy-price-box
        = link_to buyscreen_buy_path ,class: 'itembuy-price-box' do
          購入画面に進む
  .itembuy-detail
    %p.itembuy-detail__coments
      = @item.description
      
  .itembuy-button
    .itembuy-button__left
      %button{ type: 'button', name: 'iine', class: 'i fa fa-heart' }
        %span.itembuy-button-like いいね! 999
      = link_to root_path do
        %i.fa.fa-flag
          %span 不適切な商品の報告
    .itembuy-button__right
      = link_to root_path ,class: "link_color"do
        %i.fa.fa-shopping-bag
          %span あんしん・あんぜんへの取り組み
.itembuy-content-box
  .itembuy-detail-message
    .itembuy-content__comment
      %form.itembuy-message__form
        %p.form-messeage-coments 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.form-messeage-textarea
        %button.form-messeage-button
          %span コメントする
%ul.itembuy-nav
  %li.itembuy-nav__left
    = link_to root_path,class: "link_color" do
      %i.fa.fa-chevron-left
      左ブランド
  %li.itembuy-nav__right
    = link_to root_path,class: "link_color" do
      右ブランド
      %i.fa.fa-chevron-right
.itembuy-media-box
  %ul.itembuy-media-box__list
    %li.itembuy-media-boxli
      = link_to root_path do
        %i.fa.fa-facebook-square
    %li.itembuy-media-boxli
      = link_to root_path do
        %i.fa.fa-twitter-square
    %li.itembuy-media-boxli
      = link_to root_path do
        %i.fa.fa-pinterest-square
.itembuy-user-profile
  %h2.itembuy-user-profile__head
    = link_to root_path do
      g64さんのその他の出品
  .itembuy-user-profile__content
    .itembuy-user-profile__box
      %section.itembuy-user-profile__items
        = link_to root_path do
          = image_tag "testimage.jpg", size: '220x220'
          .itembuy-user-profile__body
            %h3.itembuy-user-profile__name
              g64
            .itembuy-user-profile__num
              .itembuy-user-profile__price
                1000
              .itembuy-user-profile__btn
                %i.fa.fa-heart-o.showheart
                .itembuy-user-profile__like
                  1
    .itembuy-user-profile__box
      %section.itembuy-user-profile__items
        = link_to root_path do
          = image_tag "testimage.jpg", size: '220x220'
          .itembuy-user-profile__body
            %h3.itembuy-user-profile__name
              g64
            .itembuy-user-profile__num
              .itembuy-user-profile__price
                1000
              .itembuy-user-profile__btn
                %i.fa.fa-heart-o.showheart
                .itembuy-user-profile__like
                  1
    .itembuy-user-profile__box
      %section.itembuy-user-profile__items
        = link_to root_path do
          = image_tag "testimage.jpg", size: '220x220'
          .itembuy-user-profile__body
            %h3.itembuy-user-profile__name
              g64
            .itembuy-user-profile__num
              .itembuy-user-profile__price
                1000
              .itembuy-user-profile__btn
                %i.fa.fa-heart-o.showheart
                .itembuy-user-profile__like
                  1
    .itembuy-user-profile__box
      %section.itembuy-user-profile__items
        = link_to root_path do
          = image_tag "testimage.jpg", size: '220x220'
          .itembuy-user-profile__body
            %h3.itembuy-user-profile__name
              g64
            .itembuy-user-profile__num
              .itembuy-user-profile__price
                1000
              .itembuy-user-profile__btn
                %i.fa.fa-heart-o.showheart
                .itembuy-user-profile__like
                  1

app/views/items/before_edit.html.haml
.wrapper
  = render "index/header"
  = render "delete_item"
  = render "index/download"
  = render "index/footer"

app/views/items/chenge_item.html.haml
= render "delete_item"

app/views/items/edit.html.haml
.sell
  .sel__header
    = render "shared/user_header"
  .sell__body
    = form_with(model: @item,url: item_path, method: :PATCH , local: true) do |f|
      .sell__file
        .sell-form-group
          .sell__label
            %h3.sell__block__form__upload__head
              出品画像
              %span.require 必須
            %p 最大10枚までアップロードできます
            #image-box-1
              .item-num-0#image-box__container
                = f.fields_for :images do |image|
                  .input-area
                    =image.label :image, class: "image" do
                      #img_field{:onclick => "$('#file').click()"}
                        = image_tag image.object.image.url, class: "image_now"
                        =image.file_field :image, class: "image", style: "display:none", id: "file"
      .sell__file
        .sell-form-group
          .sell__label
            商品名
            %span.require 必須
          = f.text_field :name, class: 'select_default',placeholder: "商品名（必須 40文字まで)"
          .sell-form-group
            .sell__label
              商品の説明
              %span.require 必須
            = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
      .sell__file
        .sell__head
          商品の詳細
          .sell-form-group
            .sell__label
              カテゴリー
              %span.require 必須
            = f.fields_for :item_categories do |c|
              = c.select :category_id, {レディース: 1, メンズ: 2, ベビー・キッズ: 3, インテリア・住まい・小物: "", 本・音楽・ゲーム: "", おもちゃ・ホビー・グッズ: "", コスメ・香水・美容: "", 家電・スマホ・カメラ: "", スポーツ・レジャー: "", ハンドメイド: "", チケット: "", 自動車・オートバイ: "", その他: ""}
              = c.hidden_field :id, value: c.object.id

          .sell-form-group
            .sell__label
              ブランド
              %span.anys 任意
            = f.fields_for :brands do |b|
              = b.text_field :name, class: 'select_default', placeholder: "（例）シャネル"
              = b.hidden_field :id, value: b.object.id
          .sell-form-group
            .sell__label
              商品の状態
              %span.require 必須
            = f.select :status ,新品、未使用: "新品、未使用",未使用に近い: "未使用に近い",目立った傷や汚れなし: "目立った傷や汚れなし",やや傷や汚れあり: "やや傷や汚れあり",傷や汚れあり: "傷や汚れあり",全体的に状態が悪い: "全体的に状態が悪い"
      .sell__file
        .sell__head
          配送について
          .sell-form-group
            .sell__label
              配送料の負担
              %span.require 必須
            = f.select :burden, 送料込み（出品者負担）: "送料込み（出品者負担）", 着払い（購入者負担）: "着払い（購入者負担）"
        .sell-form-group
          .sell__label
            発送方法
            %span.require 必須
          = f.select :send_method, 未定: "未定", ゆうゆうフリマ便: "ゆうゆうフリマ便", ゆうメール: "ゆうメール",クロネコヤマト: "クロネコヤマト"
        .sell-form-group
          .sell__label
            発送元の地域
            %span.require 必須
          = f.select :region,北海道: "北海道",青森県: "青森県",岩手県: "岩手県",宮城県: "宮城県",秋田県: "秋田県",山形県: "山形県",福島県: "福島県",茨城県: "茨城県",栃木県: "栃木県",群馬県: "群馬県",埼玉県: "埼玉県",千葉県: "千葉県",東京都: "東京都",神奈川県: "神奈川県",新潟県: "新潟県",富山県: "富山県",石川県: "石川県",福井県: "福井県",山梨県: "山梨県",長野県: "長野県",岐阜県: "岐阜県",静岡県: "静岡県",愛知県: "愛知県",三重県: "三重県",滋賀県: "滋賀県",京都府: "京都府",大阪府: "大阪府",兵庫県: "兵庫県",奈良県: "奈良県",和歌山県: "和歌山県",鳥取県: "鳥取県",島根県: "島根県",岡山県: "岡山県",広島県: "広島県",山口県: "山口県",徳島県: "徳島県",香川県: "香川県",愛媛県: "愛媛県",高知県: "高知県",福岡県: "福岡県",佐賀県: "佐賀県",長崎県: "長崎県",熊本県: "熊本県",大分県: "大分県",宮崎県: "宮崎県",鹿児島県: "鹿児島県",沖縄県: "沖縄県"
        .sell-form-group
          .sell__label
            発送までの日数
            %span.require 必須
          = f.select :date ,１〜２日で発送: "１〜２日で発送", ２〜３日で発送: "２〜３日で発送", ４〜７日で発送: "４〜７日で発送"
      .sell__file
        .sell__head
          販売価格(300〜9,999,999)
          .sell-form-group
            %ul.sell-price
              %li.form-group
                .sell__price
                  .sell__label
                    商品の説明
                    %span.require 必須
                  .sell-right.sell-price-input
                    .sell-yen
                      ¥
                    %div
                      = f.text_area :price, class: "input-price", placeholder: "例）300", value: ""
                / react-empty: 110
              %li.sell__fee
                .sell-left
                  / react-text: 199
                  販売手数料 (10%)
                  / /react-text
                %h9 ー
              %li.sell__fee
                .sell-left--bold 販売利益
                %h10 ー
            .sell__exhibit
              = f.submit :更新する, class: "sell-btn__red"
            .sell__back
              = link_to root_path, class: "sell-btn__grey" do
                戻る
            .sell-text
              禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .sell__footer
    = render "shared/user_footer"

app/views/items/show.html.haml
.wrapper
  = render "index/header"
  = render "product_show"
  = render "index/download"
  = render "index/footer"