config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  devise_for :users,
  controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

    resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end
  
  resources :card, only: [:index, :new, :show, :delete] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:index,:show,:new, :edit]

  resources :mypage, only: [:index] do
    get "profile"
  end
  resources :logout, only: [:index]

  resources :sell, only: [:index,:new, :create, :destroy]
  resources :items, only: [:index,:new,:show,:edit,:update,:destroy] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
      get "before_edit"
    end
  end
  resources :profile, only: [:index]
  resources :card, only: [:index] do
    collection do
      get 'mypage_card_input'
    end
  end
  resources :pribate, only: [:index]
  resources :confomation, only: [:index]
  resources :buy, only: [:index] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
    end
  end

  
  get "/mypage/exhibiting", to: "mypage#exhibiting"
  get '/mypage/notification', to: 'mypage#notification'
  get '/mypage/todo', to: 'mypage#todo'
  get '/mypage/card', to: 'mypage#card'
  get '/mypage/deliver_address', to: 'mypage#deliver_address'
  delete '/card/delete', to: 'card#delete'



end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    redirect_to action: 'show' if current_user.card.present?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials[:"pay.jp"][:"PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to done_signup_index_path
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:"pay.jp"][:"PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:"pay.jp"][:"PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/card/_card_add.html.haml
.payment-input
  .payment-input__container
    = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      .payment-input__container__title
        支払い方法
      .payment-input__container__form-name
        カード番号
        %span.require 必須
      .payment-input__container__form
        = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      .payment-card-logo
        = image_tag "visa.svg", class: "card-logo-svg"
        = image_tag "mastercard.svg", class: "card-logo-svg"
        = image_tag "saison.svg", class: "card-logo-svg"
        = image_tag "jcb.svg", class: "card-logo-svg"
        = image_tag "american-express.svg", class: "card-logo-svg"
        = image_tag "diners-club.svg", class: "card-logo-svg"
        = image_tag "discover.svg", class: "card-logo-svg"
      .payment-input__container__form-name
        有効期限
        %span.require 必須
      .payment-input__container__form-select
        .payment-input__container__form-select__month       
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月
        .payment-input__container__form-select__year
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
      .payment-input__container__form-name
        セキュリティーコード
        %span.require 必須
      .payment-input__container__form
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      .payment-input__containe__back-card
        =link_to "#",class: "back-card" do
          カード裏面の番号とは？
        .payment-input__container__next-btn
        #card_token
      = submit_tag "次へ進む", id: "token_submit"

app/views/card/_mypage_card_add.html.haml
.mypage_payment
  .mypage_payment__title
    支払い方法
  .mypage_payment__content
    .mypage_payment__content__title
      クレジットカード一覧
    .mypage_payment__content__add
      .mypage_payment__content__add_btn
        =link_to "#",class: "add_btn" do
          %i.card-icon.fa-credit-card
          %div#add_btn
            クレジットカードを追加する
      .mypage_payment__content__about
        =link_to "#" ,class: "payment_method_about" do
          支払い方法について>

app/views/card/_mypage_input_card.html.haml
.mypage-payment-input
  .payment-input__container
    = form_with(model:@card, url: registration_complete_registration_index_path, method: :get, local: true) do |f|
      .payment-input__container__title
        支払い方法
      .payment-input__container__form-name
        カード番号
        %span.required 必須
      .payment-input__container__form
        = f.text_field :card_number, placeholder: "  半角数字のみ", class: "payment-input-form"
      .payment-card-logo
        = image_tag "/assets/visa.svg", class: "card-logo-svg"
        = image_tag "/assets/mastercard.svg", class: "card-logo-svg"
        = image_tag "/assets/saison.svg", class: "card-logo-svg"
        = image_tag "/assets/jcb.svg", class: "card-logo-svg"
        = image_tag "/assets/american-express.svg", class: "card-logo-svg"
        = image_tag "/assets/diners-club.svg", class: "card-logo-svg"
        = image_tag "/assets/discover.svg", class: "card-logo-svg"
      .payment-input__container__form-name
        有効期限
        %span.required 必須
      .payment-input__container__form-select
        .payment-input__container__form-select__month       
          = f.select :payment_expiration__detail, ０１: ""
          月
        .payment-input__container__form-select__year
          = f.select :payment_expiration__detail, １９: ""
          年
      .payment-input__container__form-name
        セキュリティーコード
        %span.required 必須
      .payment-input__container__form
        = f.text_field :cvc_number, placeholder: "  カード背面4桁もしくは3桁の番号", class: "payment-input-form"
      .payment-input__containe__back-card
        =link_to "#",class: "back-card" do
          カード裏面の番号とは？
        .payment-input__container__next-btn
        = f.submit :次へ進む, class: "payment-next_btn"

app/views/card/index.html.haml
.mypage-header
  = render "index/loginheader"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
      = render "card/mypage_card_add"
      -# 後ほどの条件分岐用にコメントアウト 
      -# = render "mypage_card_delete"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/card/mypage_card_input.html.haml
.mypage-header
  = render "index/loginheader"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
      = render "mypage_input_card"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/card/mypage_input_card.html.haml
.mypage-payment-input
  .payment-input__container
    = form_with(model:@card, url: registration_complete_registration_index_path, method: :get, local: true) do |f|
      .payment-input__container__title
        支払い方法
      .payment-input__container__form-name
        カード番号
        %span.require 必須
      .payment-input__container__form
        = f.text_field :card_number, placeholder: "  半角数字のみ", class: "payment-input-form"
      .payment-card-logo
        = image_tag "visa.svg", class: "card-logo-svg"
        = image_tag "mastercard.svg", class: "card-logo-svg"
        = image_tag "saison.svg", class: "card-logo-svg"
        = image_tag "jcb.svg", class: "card-logo-svg"
        = image_tag "american-express.svg", class: "card-logo-svg"
        = image_tag "diners-club.svg", class: "card-logo-svg"
        = image_tag "discover.svg", class: "card-logo-svg"
      .payment-input__container__form-name
        有効期限
        %span.require 必須
      .payment-input__container__form-select
        .payment-input__container__form-select__month       
          = f.select :payment_expiration__detail, ０１: ""
          月
        .payment-input__container__form-select__year
          = f.select :payment_expiration__detail, １９: ""
          年
      .payment-input__container__form-name
        セキュリティーコード
        %span.require 必須
      .payment-input__container__form
        = f.text_field :cvc_number, placeholder: "  カード背面4桁もしくは3桁の番号", class: "payment-input-form"
      .payment-input__containe__back-card
        =link_to "#",class: "back-card" do
          カード裏面の番号とは？
        .payment-input__container__next-btn
        = f.submit :次へ進む, class: "payment-next_btn"

app/views/card/new.html.haml
.mypage-header
  = render "index/loginheader"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
      = render "mypage_card_add.html"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/card/show.html.haml
.mypage-header
  = render "index/loginheader"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
      .mypage_payment
        .mypage_payment__title
          支払い方法
        .mypage_payment__content
          .mypage_payment__content__title
            クレジットカード一覧
            - if @card.blank?
              .card-company-logos
                = image_tag "visa.svg", class: "card-logo-svg" 
                .mypage_payment__title__container
                  .mypage_payment_text
                  = "**** **** **** " + @default_card_information.last4
                  %br
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
                .card_delete_btn
                  = form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
                    %input{ type: "hidden", name: "card_id", value: "" }
                    %span 削除する
              .mypage_payment__content__about
                =link_to "#" ,class: "payment_method_about" do
                  支払い方法について>
            - else
              .mypage_payment__content__add_btn
                =link_to mypage_card_new_path do
                  %i.card-icon.fa-credit-card
                  %div#add_btn
                    クレジットカードを追加する
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"