config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  devise_for :users,
  controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

    resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end
  
  resources :card, only: [:index, :new, :show, :delete] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:index,:show,:new, :edit]

  resources :mypage, only: [:index] do
    get "profile"
  end
  resources :logout, only: [:index]

  resources :sell, only: [:index,:new, :create, :destroy]
  resources :items, only: [:index,:new,:show,:edit,:update,:destroy] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
      get "before_edit"
    end
  end
  resources :profile, only: [:index]
  resources :card, only: [:index] do
    collection do
      get 'mypage_card_input'
    end
  end
  resources :pribate, only: [:index]
  resources :confomation, only: [:index]
  resources :buy, only: [:index] do
    member do
      get 'buyscreen'
      post 'buyscreenitem'
    end
  end

  
  get "/mypage/exhibiting", to: "mypage#exhibiting"
  get '/mypage/notification', to: 'mypage#notification'
  get '/mypage/todo', to: 'mypage#todo'
  get '/mypage/card', to: 'mypage#card'
  get '/mypage/deliver_address', to: 'mypage#deliver_address'
  delete '/card/delete', to: 'card#delete'



end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def profile
  end

  def notification
  end

  def todo
  end

  def card
  end

  def deliver_address
  end

  def exhibiting
    @items = Item.where(seler_id: current_user.id)
    
  end
  private
  def set_item
    @item = Item.find(params[:id])
  end

  def set_user
    @user = User.find(id:current_user.id)
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/_like_all.html.haml
.like_all
  いいね！一覧
.like_list
  %ul.mypage-item-list
    %li#mypage-item-none いいね！がありません

app/views/mypage/_mypage.html.haml
%section#mypage__user-icon
  = link_to "#", class: "mypage_link" do
    %figure#figureimg
      = image_tag "member.png", class: "mypageicon"
    %div#mypageicon-name
      = current_user.nickname
  .mypage__number
    %div#my-evaluate
      評価　0
    %div
      出品数　0

app/views/mypage/_mypage_card_add.html.haml
.mypage_payment
  .mypage_payment__title
    支払い方法
  .mypage_payment__content
    .mypage_payment__content__title
      クレジットカード一覧
    .mypage_payment__content__add
      -# - if card_add_in?
      -# カードの登録がある場合
      -# - else
      .mypage_payment__content__add_btn
        =link_to "#",class: "add_btn" do
          %i.card-icon.fa-credit-card
          %div#add_btn
            クレジットカードを追加する
      .mypage_payment__content__about
        =link_to "#",class: "payment_method_about" do
          支払い方法について>

app/views/mypage/_mypage_card_input.html.haml
.mypage-payment-input
  .payment-input__container
    = form_with(model:@card, url: registration_complete_registration_index_path, method: :get, local: true) do |f|
      .payment-input__container__title
        支払い方法
      .payment-input__container__form-name
        カード番号
        %span.required 必須
      .payment-input__container__form
        = f.text_field :card_number, placeholder: "  半角数字のみ", class: "payment-input-form"
      .payment-card-logo
        = image_tag "/assets/visa.svg", class: "card-logo-svg"
        = image_tag "/assets/mastercard.svg", class: "card-logo-svg"
        = image_tag "/assets/saison.svg", class: "card-logo-svg"
        = image_tag "/assets/jcb.svg", class: "card-logo-svg"
        = image_tag "/assets/american-express.svg", class: "card-logo-svg"
        = image_tag "/assets/diners-club.svg", class: "card-logo-svg"
        = image_tag "/assets/discover.svg", class: "card-logo-svg"
      .payment-input__container__form-name
        有効期限
        %span.required 必須
      .payment-input__container__form-select
        .payment-input__container__form-select__month       
          = f.select :payment_expiration__detail, ０１: ""
          月
        .payment-input__container__form-select__year
          = f.select :payment_expiration__detail, １９: ""
          年
      .payment-input__container__form-name
        セキュリティーコード
        %span.required 必須
      .payment-input__container__form
        = f.text_field :cvc_number, placeholder: "  カード背面4桁もしくは3桁の番号", class: "payment-input-form"
      .payment-input__containe__back-card
        =link_to "#",class: "back-card" do
          カード裏面の番号とは？
        .payment-input__container__next-btn
        = f.submit :次へ進む, class: "payment-next_btn"

app/views/mypage/_mypage_item_list.html.haml
%ul.mypage-item-list
  %img#mypage-item-none{src: "logo_red.svg"}

app/views/mypage/_mypage_sidebar.html.haml
.mypage_side
  %ul#mypage_side__list
    %li.mypage_side__menu
      = link_to mypage_index_path,class: "mypage_side__list__item" do
        マイページ
    %li.mypage_side__menu
      = link_to mypage_notification_path, class: "mypage_side__list__item" do
        お知らせ
    %li.mypage_side__menu
      = link_to mypage_todo_path,class: "mypage_side__list__item" do
        やることリスト
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        いいね！一覧
    %li.mypage_side__menu
      = link_to new_sell_path, class: "mypage_side__list__item" do
        出品する
    %li.mypage_side__menu
      = link_to mypage_exhibiting_path,class: "mypage_side__list__item" do
        出品した商品 - 出品中
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        出品した商品 - 取引中
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        出品した商品 - 売却中
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        購入した商品 - 取引中
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        購入した商品 - 過去の過去の取引
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        ニュース一覧
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        評価一覧
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        ガイド
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        お問い合わせ
  .mypage_side__title
    フリペイ
  %ul#mypage_side__list
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        売上・振込申請
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        ポイント
  .mypage_side__title
    設定
  %ul#mypage_side__list
    %li.mypage_side__menu
      = link_to profile_index_path, class: "mypage_side__list__item" do
        プロフィール
    %li.mypage_side__menu
      = link_to mypage_deliver_address_path, class: "mypage_side__list__item" do
        発送元・お届け先住所変更
    %li.mypage_side__menu
      = link_to mypage_card_input_card_index_path,class: "mypage_side__list__item" do
        支払い方法
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        メール/パスワード
    %li.mypage_side__menu
      = link_to pribate_index_path,class: "mypage_side__list__item" do
        本人情報
    %li.mypage_side__menu
      = link_to "#",class: "mypage_side__list__item" do
        電話番号の確認
    %li.mypage_side__menu
      = link_to logout_index_path, class: "mypage_side__list__item" do
        ログアウト

app/views/mypage/_notification.html.haml
.mypage-tab-container-notification-todo
  %ul#mypage_tabs
    %li#my_list
      = link_to mypage_notification_path,class: "my-notice__active" do
        お知らせ
    %li#my_list
      = link_to mypage_todo_path,class: "my-notice" do
        やることリスト

  %ul.mypage-item-lists
    %li#mypage-item-none 
      現在、お知らせはありません
    %li#mypage-go-list
      = link_to "#", class: "summary" do
        一覧を見る

app/views/mypage/_notificationhtml.haml
%selection#mypage-tab-container-notification-todo
  %ul#mypage_tabs
    %li#my_list
      = link_to "#", class: "my-notice" do
        お知らせ
      #mypage-message
        = link_to "#", class: "my_message" do
          ログインのお知らせ
    %li:active#my_list
      = link_to "#", class: "my-notice" do
        やることリスト
      #mypage-message
        = link_to "#", class: "my_message" do
          ログインのお知らせ

%ul#mypage-todo
  %li#mypage-message
    = link_to "#", class: "my_message" do
      ログインのお知らせ
  %li#mypage-go-list
    = link_to "#", class: "summary" do
      一覧を見る

app/views/mypage/_profile.html.haml
.profile
  = form_with(model: @user, local: true) do |f|
    .profile__title
      プロフィール
    .profile__logo
      .profile__image
        = image_tag "member.png", class: "profile-icon"
      .profile__name
        = f.text_field :profile_namearea
    .profile__text
      .profile__text__form
        = f.text_area  :profile_text_area, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"
      .profile__submit
        = f.submit :変更する, class: "profile__btn"

app/views/mypage/_todo.html.haml
.mypage-tab-container-notification-todo
  %ul#mypage_tabs
    %li#my_list
      = link_to mypage_notification_path,class: "my-notice" do
        お知らせ
    %li#my_list
      = link_to mypage_todo_path,class: "my-notice__active" do
        やることリスト

  %ul.mypage-item-list
    %li#mypage-item-none 
      現在、お知らせはありません
    %li#mypage-go-list
      = link_to "#", class: "summary" do
        現在、やることリストはありません

app/views/mypage/deliver_address.html.haml
.mypage-header
  = render "index/header"
  - breadcrumb :mypage
  = render "index/bread-crumbs"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
    .pribate__right
      = form_with(model: @user, local: true) do |f|
        .pribate__title
          発送元・お届け先住所変更
        .member-info__name
          .member-info__field--label
            お名前
            %span.member-info__field--required
              必須
        .member-info__field--placeholder
          .member-info__box
            = f.text_field :last_name, autofocus: true, placeholder: "例）山田",class: "member-info__field--input"
          .member-info__box
            = f.text_field :fast_name, autofocus: true, placeholder: "例）彩",class: "member-info__field--input"
        .member-info__name
          .member-info__field--label
            お名前カナ
            %span.member-info__field--required
              必須
        .member-info__field--placeholder
          .member-info__box
            = f.text_field :last_name, autofocus: true, placeholder: "例）山田",class: "member-info__field--input"
          .member-info__box
            = f.text_field :fast_name, autofocus: true, placeholder: "例）彩",class: "member-info__field--input"
        .address-input__container__form-name
          郵便番号
          %span.require 必須
          .address-input__container__form
            = f.text_field :postal_code, placeholder: "例) 123-4567", type: "text", class: "member-info__field--input",required:"required"
          .address-input__container__form-name
            都道府県
            %span.require 必須
          .address-input__container__form
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "--"}, {class: "member-info__field--input"}
          .address-input__container__form-name
            市区町村
            %span.require 必須
          .address-input__container__form
            = f.text_field :city, placeholder: "例) 横浜市緑区", type: "text", class: "member-info__field--input",required:"required"
          .address-input__container__form-name
            番地
            %span.require 必須
          .address-input__container__form
          = f.text_field :address, placeholder: "例) 青山1-1-1", type: "text", class: "member-info__field--input",required:"required"
          .address-input__container__form-name
            建物名
            %span.any 任意
          .address-input__container__form
            = f.text_field :building_name, placeholder: "例) 柳ビル103", type: "text", class: "addres-input_form"
          .address-input__container__form-name
            電話
            %span.any 任意
          .address-input__container__form
            = f.text_field :phone_number, placeholder: "例) 09012345678", type: "text", class: "addres-input_form"
          = f.submit :次へ進む, class: "next_btn"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/mypage/index.html.haml
.mypage-header
  = render "index/header"
  - breadcrumb :mypage
  = render "index/bread-crumbs"
  .mypage
    .mypage__left
      = render "mypage_sidebar"
    .mypage__right
      = render "mypage"
      .mypage-tab-center
        = render "notification"
      .mypage-tab-container
        = render "past_transactions"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/mypage/mypage_card.html.haml
.mypage-header
  = render "index/header"
  .mypage
    .mypage__left
      = render "mypage_sidebar"
    .mypage__right
      = render "mypage_card_add"
      -# = render "mypage_card_input"
      -# = render "mypage_card_delete"
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"

app/views/mypage/notification.html.haml
.mypage-header
  = render "index/header"
  - breadcrumb :mypage
  = render "index/bread-crumbs"
  .mypage
    .mypage__left
      = render "mypage/mypage_sidebar"
    .mypage__right
      .mypage-tab-container-notification-todo
        %ul#mypage_tabs
          %li#my_list
            = link_to mypage_notification_path,class: "my-notice__active" do
              お知らせ
          %li#my_list
            = link_to mypage_todo_path ,class: "my-notice" do
              やることリスト

        %ul.mypage-item-list
          %li#mypage-item-none 
            現在、お知らせはありません
.mypage-footer
  = render "index/download"
  = render "index/footer"
  = render "index/exhibit"